# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wanfang.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wanfang.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rwanfang.proto\"\xf6\x02\n\rSearchService\x1a\x87\x02\n\rCommonRequest\x12\x12\n\nsearchType\x18\x01 \x01(\t\x12\x12\n\nsearchWord\x18\x02 \x01(\t\x12\x13\n\x0b\x63urrentPage\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x12\x31\n\x0csearchFilter\x18\x05 \x03(\x0e\x32\x1b.SearchService.SearchFilter\x12;\n\nsearchSort\x18\x06 \x03(\x0b\x32\'.SearchService.CommonRequest.SearchSort\x12\x13\n\x0bsearchScope\x18\x07 \x01(\x05\x1a\"\n\nSearchSort\x12\t\n\x01\x42\x18\x01 \x01(\t\x12\t\n\x01\x43\x18\x02 \x01(\x05\x1a\x44\n\rSearchRequest\x12\x33\n\rcommonRequest\x18\x01 \x01(\x0b\x32\x1c.SearchService.CommonRequest\"\x15\n\x0cSearchFilter\x12\x05\n\x01\x41\x10\x00\x62\x06proto3')
)



_SEARCHSERVICE_SEARCHFILTER = _descriptor.EnumDescriptor(
  name='SearchFilter',
  full_name='SearchService.SearchFilter',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='A', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=371,
  serialized_end=392,
)
_sym_db.RegisterEnumDescriptor(_SEARCHSERVICE_SEARCHFILTER)


_SEARCHSERVICE_COMMONREQUEST_SEARCHSORT = _descriptor.Descriptor(
  name='SearchSort',
  full_name='SearchService.CommonRequest.SearchSort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='B', full_name='SearchService.CommonRequest.SearchSort.B', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='C', full_name='SearchService.CommonRequest.SearchSort.C', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=299,
)

_SEARCHSERVICE_COMMONREQUEST = _descriptor.Descriptor(
  name='CommonRequest',
  full_name='SearchService.CommonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='searchType', full_name='SearchService.CommonRequest.searchType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchWord', full_name='SearchService.CommonRequest.searchWord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='SearchService.CommonRequest.currentPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='SearchService.CommonRequest.pageSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchFilter', full_name='SearchService.CommonRequest.searchFilter', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchSort', full_name='SearchService.CommonRequest.searchSort', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='searchScope', full_name='SearchService.CommonRequest.searchScope', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEARCHSERVICE_COMMONREQUEST_SEARCHSORT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=299,
)

_SEARCHSERVICE_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='SearchService.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commonRequest', full_name='SearchService.SearchRequest.commonRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=369,
)

_SEARCHSERVICE = _descriptor.Descriptor(
  name='SearchService',
  full_name='SearchService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SEARCHSERVICE_COMMONREQUEST, _SEARCHSERVICE_SEARCHREQUEST, ],
  enum_types=[
    _SEARCHSERVICE_SEARCHFILTER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=392,
)

_SEARCHSERVICE_COMMONREQUEST_SEARCHSORT.containing_type = _SEARCHSERVICE_COMMONREQUEST
_SEARCHSERVICE_COMMONREQUEST.fields_by_name['searchFilter'].enum_type = _SEARCHSERVICE_SEARCHFILTER
_SEARCHSERVICE_COMMONREQUEST.fields_by_name['searchSort'].message_type = _SEARCHSERVICE_COMMONREQUEST_SEARCHSORT
_SEARCHSERVICE_COMMONREQUEST.containing_type = _SEARCHSERVICE
_SEARCHSERVICE_SEARCHREQUEST.fields_by_name['commonRequest'].message_type = _SEARCHSERVICE_COMMONREQUEST
_SEARCHSERVICE_SEARCHREQUEST.containing_type = _SEARCHSERVICE
_SEARCHSERVICE_SEARCHFILTER.containing_type = _SEARCHSERVICE
DESCRIPTOR.message_types_by_name['SearchService'] = _SEARCHSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchService = _reflection.GeneratedProtocolMessageType('SearchService', (_message.Message,), {

  'CommonRequest' : _reflection.GeneratedProtocolMessageType('CommonRequest', (_message.Message,), {

    'SearchSort' : _reflection.GeneratedProtocolMessageType('SearchSort', (_message.Message,), {
      'DESCRIPTOR' : _SEARCHSERVICE_COMMONREQUEST_SEARCHSORT,
      '__module__' : 'wanfang_pb2'
      # @@protoc_insertion_point(class_scope:SearchService.CommonRequest.SearchSort)
      })
    ,
    'DESCRIPTOR' : _SEARCHSERVICE_COMMONREQUEST,
    '__module__' : 'wanfang_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.CommonRequest)
    })
  ,

  'SearchRequest' : _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHSERVICE_SEARCHREQUEST,
    '__module__' : 'wanfang_pb2'
    # @@protoc_insertion_point(class_scope:SearchService.SearchRequest)
    })
  ,
  'DESCRIPTOR' : _SEARCHSERVICE,
  '__module__' : 'wanfang_pb2'
  # @@protoc_insertion_point(class_scope:SearchService)
  })
_sym_db.RegisterMessage(SearchService)
_sym_db.RegisterMessage(SearchService.CommonRequest)
_sym_db.RegisterMessage(SearchService.CommonRequest.SearchSort)
_sym_db.RegisterMessage(SearchService.SearchRequest)


# @@protoc_insertion_point(module_scope)
